CREATE TABLE [dbo].[fulfilling_commitments_sql] (

	[company_id] int NULL, 
	[plant] varchar(8000) NULL, 
	[area] varchar(8000) NULL, 
	[quantity] int NULL, 
	[company_code_co] varchar(8000) NULL, 
	[delivery_unit] varchar(8000) NULL, 
	[total_comp] int NULL, 
	[usr_name2] varchar(8000) NULL, 
	[proj_id] varchar(8000) NULL, 
	[usr_name] varchar(8000) NULL, 
	[total] int NULL, 
	[company_code_fi] varchar(8000) NULL, 
	[quantity_comp] int NULL, 
	[indicator_name] varchar(8000) NULL, 
	[origin_id] varchar(8000) NULL, 
	[type_agreement] int NULL, 
	[sublevel] varchar(8000) NULL, 
	[task_effectiveness] varchar(8000) NULL, 
	[work_center] varchar(8000) NULL, 
	[support_process] varchar(8000) NULL, 
	[task_iscompleted] bit NULL, 
	[date_completed] varchar(8000) NULL, 
	[storage] varchar(8000) NULL, 
	[transaction_date] varchar(8000) NULL, 
	[name_agreement] varchar(8000) NULL, 
	[number_indicator] int NULL, 
	[tipo_objeto_medicion] varchar(8000) NULL, 
	[seller] varchar(8000) NULL, 
	[sales_org] varchar(8000) NULL, 
	[task_description] varchar(8000) NULL, 
	[contract] varchar(8000) NULL, 
	[deposit_ts] datetime2(6) NULL
);