CREATE TABLE [md].[calendar] (

	[date_id] int NULL, 
	[full_date] date NULL, 
	[year] int NULL, 
	[quarter] int NULL, 
	[quarter_name] varchar(8000) NULL, 
	[month] int NULL, 
	[month_name] varchar(8000) NULL, 
	[month_short_name] varchar(8000) NULL, 
	[week_of_year] int NULL, 
	[week_of_month] int NULL, 
	[day_of_week] int NULL, 
	[day_of_week_name] varchar(8000) NULL, 
	[day_of_month] int NULL, 
	[day_of_year] int NULL, 
	[is_weekend] bit NULL, 
	[is_holiday] bit NULL, 
	[holiday_name] varchar(8000) NULL, 
	[is_holiday_fixed] bit NULL, 
	[holiday_name_fixed] varchar(8000) NULL, 
	[is_holiday_observed] bit NULL, 
	[holiday_name_observed] varchar(8000) NULL, 
	[is_business_day] bit NULL, 
	[fiscal_year] int NULL, 
	[fiscal_quarter] varchar(8000) NULL, 
	[fiscal_month] int NULL, 
	[iso_week] int NULL, 
	[last_updated_at] datetime2(6) NULL
);