CREATE TABLE [md].[process_log_history] (

	[type_code] varchar(8000) NULL, 
	[document_id] varchar(8000) NULL, 
	[sq] decimal(2,0) NULL, 
	[ln] decimal(2,0) NULL, 
	[material_id] varchar(8000) NULL, 
	[addr] varchar(8000) NULL, 
	[type_code_addr] varchar(8000) NULL, 
	[quantity] decimal(15,3) NULL, 
	[amount] decimal(15,3) NULL, 
	[date] datetime2(6) NULL, 
	[userreg] varchar(8000) NULL, 
	[date_registered] datetime2(6) NULL, 
	[time_registered] varchar(8000) NULL, 
	[aut] bit NULL, 
	[useraut] varchar(8000) NULL, 
	[dataut] datetime2(6) NULL, 
	[timaut] varchar(8000) NULL, 
	[remarks_1] varchar(8000) NULL, 
	[remarks_2] varchar(8000) NULL, 
	[remarks_3] varchar(8000) NULL, 
	[remarks_4] varchar(8000) NULL, 
	[remarks_5] varchar(8000) NULL, 
	[arch] varchar(8000) NULL, 
	[src] varchar(8000) NULL, 
	[currency_code] varchar(8000) NULL, 
	[exchange_rate] decimal(10,4) NULL, 
	[company_code] varchar(8000) NULL, 
	[record_id] bigint NULL, 
	[last_updated_at] datetime2(6) NULL
);