CREATE TABLE [md].[user_master] (

	[user_id] varchar(8000) NULL, 
	[lang] varchar(8000) NULL, 
	[user1] varchar(8000) NULL, 
	[user2] varchar(8000) NULL, 
	[plant_id] varchar(8000) NULL, 
	[passwd] varchar(8000) NULL, 
	[name] varchar(8000) NULL, 
	[last_date] datetime2(6) NULL, 
	[restrict] int NULL, 
	[address_id] varchar(8000) NULL, 
	[mail_address] varchar(8000) NULL, 
	[type] varchar(8000) NULL, 
	[timezone] varchar(8000) NULL, 
	[access_type] varchar(8000) NULL, 
	[storage_location_id] varchar(8000) NULL, 
	[ctry_code] varchar(8000) NULL, 
	[variant_code] varchar(8000) NULL, 
	[failed_attempts] int NULL, 
	[force_change] int NULL, 
	[logon_date] datetime2(6) NULL, 
	[active] int NULL, 
	[active_by] varchar(8000) NULL, 
	[active_reason] varchar(8000) NULL, 
	[active_date] datetime2(6) NULL, 
	[logon_timezone] varchar(8000) NULL, 
	[remark] varchar(8000) NULL, 
	[logon_time] int NULL, 
	[tzdb] varchar(8000) NULL, 
	[record_id] int NULL, 
	[last_updated_at] datetime2(6) NULL
);