CREATE TABLE [QAD].[XXCON_MSTR] (

	[XXCON_CLAVE] varchar(8000) NULL, 
	[XXCON_DESC] varchar(8000) NULL, 
	[XXCON_TIPO] varchar(8000) NULL, 
	[XXCON_NEM] varchar(8000) NULL, 
	[XXCON_ACUM] smallint NULL, 
	[XXCON_CALC] smallint NULL, 
	[XXCON_GIMSS] varchar(8000) NULL, 
	[XXCON_GISPT] varchar(8000) NULL, 
	[XXCON_INTNAT] smallint NULL, 
	[XXCON_ACNAT] smallint NULL, 
	[XXCON_ACFIX] varchar(8000) NULL, 
	[XXCON_ACVAR] varchar(8000) NULL, 
	[XXCON_ACSTAD_FIX] varchar(8000) NULL, 
	[XXCON_ACSTAD_VAR] varchar(8000) NULL, 
	[XXCON_APPLYCC] smallint NULL, 
	[XXCON_CANC_LIAB] smallint NULL, 
	[XXCON_ACC_LIAB] varchar(8000) NULL, 
	[XXCON__CHR01] varchar(8000) NULL, 
	[XXCON__CHR02] varchar(8000) NULL, 
	[XXCON__CHR03] varchar(8000) NULL, 
	[XXCON__CHR04] varchar(8000) NULL, 
	[XXCON__DEC01] float NULL, 
	[XXCON__DEC02] float NULL, 
	[XXCON_ACPROV] varchar(8000) NULL, 
	[XXCON_CONCILIATE] smallint NULL, 
	[XXCON_DOMAIN] varchar(8000) NULL, 
	[OID_XXCON_MSTR] decimal(38,18) NULL, 
	[PROGRESS_RECID] decimal(38,18) NULL
);