CREATE TABLE [QAD].[XXTITLEH_HIST] (

	[XXTITLEH_ADDR] varchar(8000) NULL, 
	[XXTITLEH_PRE_TITLE] varchar(8000) NULL, 
	[XXTITLEH_TITLE] varchar(8000) NULL, 
	[XXTITLEH_PRE_DEPART] varchar(8000) NULL, 
	[XXTITLEH_XXTITLEH_INITIAL_DATE] datetime2(6) NULL, 
	[XXTITLEH_XXTITLEH_FINISH_DATE] datetime2(6) NULL, 
	[XXTITLEH_CREATE_DATE] datetime2(6) NULL, 
	[XXTITLEH_CREATE_USRID] varchar(8000) NULL, 
	[XXTITLEH_ENTWK_ADDR] varchar(8000) NULL, 
	[XXTITLEH__CHR01] varchar(8000) NULL, 
	[XXTITLEH__CHR02] varchar(8000) NULL, 
	[XXTITLEH__CHR03] varchar(8000) NULL, 
	[XXTITLEH__DAT01] datetime2(6) NULL, 
	[XXTITLEH__DAT02] datetime2(6) NULL, 
	[XXTITLEH__DAT03] datetime2(6) NULL, 
	[XXTITLEH__LOG01] smallint NULL, 
	[XXTITLEH__LOG02] smallint NULL, 
	[XXTITLEH__LOG03] smallint NULL, 
	[XXTITLEH_DOMAIN] varchar(8000) NULL, 
	[PROGRESS_RECID] int NULL
);