CREATE TABLE [QAD].[XXTITLED_DET] (

	[XXTITLED_ID] varchar(8000) NULL, 
	[XXTITLED_ENTITY] varchar(8000) NULL, 
	[XXTITLED_ENTWK_ADDR] varchar(8000) NULL, 
	[XXTITLED_MEMBERS] smallint NULL, 
	[XXTITLED_LEVEL] smallint NULL, 
	[XXTITLED_LEVELTAB] varchar(8000) NULL, 
	[XXTITLED__CHR01] varchar(8000) NULL, 
	[XXTITLED__CHR02] varchar(8000) NULL, 
	[XXTITLED__CHR03] varchar(8000) NULL, 
	[XXTITLED__DEC01] decimal(38,18) NULL, 
	[XXTITLED__DEC02] decimal(38,18) NULL, 
	[XXTITLED__DEC03] decimal(38,18) NULL, 
	[XXTITLED__LOG01] decimal(38,18) NULL, 
	[XXTITLES__DTE01] datetime2(6) NULL, 
	[XXTITLED_DOMAIN] varchar(8000) NULL, 
	[OID_XXTITLED_DET] decimal(38,18) NULL, 
	[PROGRESS_RECID] int NULL
);