CREATE TABLE [aa].[asset_budget_details] (

	[fixed_asset_id] varchar(8000) NULL, 
	[fabk_seq] int NULL, 
	[fabk_id] varchar(8000) NULL, 
	[famt_id] varchar(8000) NULL, 
	[life] int NULL, 
	[date] datetime2(6) NULL, 
	[amt] decimal(38,10) NULL, 
	[ovrdt] datetime2(6) NULL, 
	[ovramt] decimal(38,10) NULL, 
	[salvamt] decimal(38,10) NULL, 
	[resrv] int NULL, 
	[uplife] int NULL, 
	[upper] int NULL, 
	[unit_of_measure_code] varchar(8000) NULL, 
	[famtr_id] varchar(8000) NULL, 
	[upcost] int NULL, 
	[cst_adjper] varchar(8000) NULL, 
	[mod_userid] varchar(8000) NULL, 
	[mod_date] datetime2(6) NULL, 
	[user1] varchar(8000) NULL, 
	[user2] varchar(8000) NULL, 
	[chr01] varchar(8000) NULL, 
	[dec01] int NULL, 
	[log01] int NULL, 
	[dte01] datetime2(6) NULL, 
	[int01] int NULL, 
	[int02] int NULL, 
	[dec02] int NULL, 
	[company_code] varchar(8000) NULL, 
	[record_id] int NULL, 
	[last_updated_at] datetime2(6) NULL
);