CREATE TABLE [pp].[production_order_routing] (

	[production_order_number] varchar(8000) NULL, 
	[operation_number] varchar(8000) NULL, 
	[operation_description] varchar(8000) NULL, 
	[work_center_id] varchar(8000) NULL, 
	[machines_per_operation] smallint NULL, 
	[quantity_ordered] decimal(38,10) NULL, 
	[quantity_in_wip] decimal(38,10) NULL, 
	[quantity_completed] decimal(38,10) NULL, 
	[quantity_rejected] decimal(38,10) NULL, 
	[quantity_rework] decimal(38,10) NULL, 
	[operation_status] varchar(8000) NULL, 
	[start_date] date NULL, 
	[due_date] date NULL, 
	[lot_number] varchar(8000) NULL, 
	[part_number] varchar(8000) NULL, 
	[comment_index] int NULL, 
	[machine_id] varchar(8000) NULL, 
	[user_field_1] varchar(8000) NULL, 
	[user_field_2] varchar(8000) NULL, 
	[company_code] varchar(8000) NULL, 
	[record_id] int NULL, 
	[last_updated_at] datetime2(6) NULL
);