ALTER TABLE QAD.UPDT_LOG
 DROP PRIMARY KEY CASCADE;

DROP TABLE QAD.UPDT_LOG CASCADE CONSTRAINTS;

CREATE TABLE QAD.UPDT_LOG
(
  TABLE_NAME      VARCHAR2(80 BYTE),
  RECORD_ID       INTEGER,
  COMPANY_CODE    VARCHAR2(8 BYTE),
  OPERATION_TYPE  CHAR(1 BYTE),
  UPDATED_AT      DATE,
  UPDATED_BY      VARCHAR2(80 BYTE)
)
TABLESPACE TOOLS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX QAD.PK_UPDT_LOG_GEN ON QAD.UPDT_LOG
(TABLE_NAME, RECORD_ID, COMPANY_CODE)
LOGGING
TABLESPACE TOOLS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE QAD.UPDT_LOG ADD (
  CONSTRAINT CHK_OPERATION_TYPE
 CHECK (OPERATION_TYPE IN ('I', 'U', 'D')),
  CONSTRAINT PK_UPDT_LOG_GEN
 PRIMARY KEY
 (TABLE_NAME, RECORD_ID, COMPANY_CODE)
    USING INDEX 
    TABLESPACE TOOLS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

