CREATE TABLE [QAD].[XXLOG_HIST] (

	[XXLOG_TYPE] varchar(8000) NULL, 
	[XXLOG_NBR] varchar(8000) NULL, 
	[XXLOG_SQ] smallint NULL, 
	[XXLOG_LN] smallint NULL, 
	[XXLOG_PART] varchar(8000) NULL, 
	[XXLOG_ADDR] varchar(8000) NULL, 
	[XXLOG_TYPE_ADDR] varchar(8000) NULL, 
	[XXLOG_QTY] float NULL, 
	[XXLOG_AMT] float NULL, 
	[XXLOG_DATE] datetime2(6) NULL, 
	[XXLOG_USERREG] varchar(8000) NULL, 
	[XXLOG_DATREG] datetime2(6) NULL, 
	[XXLOG_TIMREG] varchar(8000) NULL, 
	[XXLOG_AUT] smallint NULL, 
	[XXLOG_USERAUT] varchar(8000) NULL, 
	[XXLOG_DATAUT] datetime2(6) NULL, 
	[XXLOG_TIMAUT] varchar(8000) NULL, 
	[XXLOG_RMKS##1] varchar(8000) NULL, 
	[XXLOG_RMKS##2] varchar(8000) NULL, 
	[XXLOG_RMKS##3] varchar(8000) NULL, 
	[XXLOG_RMKS##4] varchar(8000) NULL, 
	[XXLOG_RMKS##5] varchar(8000) NULL, 
	[XXLOG_ARCH] varchar(8000) NULL, 
	[XXLOG_SRC] varchar(8000) NULL, 
	[XXLOG_CURR] varchar(8000) NULL, 
	[XXLOG_EX_RATE] float NULL, 
	[XXLOG_DOMAIN] varchar(8000) NULL, 
	[OID_XXLOG_HIST] decimal(38,18) NULL, 
	[PROGRESS_RECID] decimal(38,18) NULL
);