CREATE TABLE [QAD].[XXTICKETD_DET] (

	[XXTICKETD_NBR] bigint NULL, 
	[XXTICKETD_PT] smallint NULL, 
	[XXTICKETD_GROSSW] bigint NULL, 
	[XXTICKETD_NETW] bigint NULL, 
	[XXTICKETD_UM] varchar(8000) NULL, 
	[XXTICKETD_LINE] varchar(8000) NULL, 
	[XXTICKETD_TIME] varchar(8000) NULL, 
	[XXTICKETD_DOMAIN] varchar(8000) NULL, 
	[OID_XXTICKETD_DET] decimal(38,10) NULL
);