CREATE TABLE [fi].[accounts_receivable_items] (

	[document_id] varchar(8000) NULL, 
	[line_type] varchar(8000) NULL, 
	[account_id] varchar(8000) NULL, 
	[cost_center_id] varchar(8000) NULL, 
	[amount] decimal(38,10) NULL, 
	[discount_amount] decimal(38,10) NULL, 
	[currency_amount] decimal(38,10) NULL, 
	[currency_discount_amount] decimal(38,10) NULL, 
	[line_text] varchar(8000) NULL, 
	[reference_text] varchar(8000) NULL, 
	[tax_code] varchar(8000) NULL, 
	[tax_indicator] varchar(8000) NULL, 
	[tax_attribute] varchar(8000) NULL, 
	[tax_usage] varchar(8000) NULL, 
	[entity_code] varchar(8000) NULL, 
	[project_code] varchar(8000) NULL, 
	[exchange_rate] decimal(38,10) NULL, 
	[exchange_rate_2] decimal(38,10) NULL, 
	[exchange_rate_type] varchar(8000) NULL, 
	[exchange_rate_sequence] int NULL, 
	[dunning_procedure_code] varchar(8000) NULL, 
	[dunning_document_id] varchar(8000) NULL, 
	[deduction_number] int NULL, 
	[subaccount] varchar(8000) NULL, 
	[user_field_1] varchar(8000) NULL, 
	[user_field_2] varchar(8000) NULL, 
	[company_code] varchar(8000) NULL, 
	[record_id] bigint NULL, 
	[last_updated_at] datetime2(6) NULL
);