CREATE TABLE [fi].[expenses] (

	[account_id] varchar(8000) NULL, 
	[category_ac_id] varchar(8000) NULL, 
	[format_position_id] varchar(8000) NULL, 
	[cost_center_id] varchar(8000) NULL, 
	[category_cc_id] varchar(8000) NULL, 
	[entry_date] date NULL, 
	[entry_date_id] int NULL, 
	[effective_date] date NULL, 
	[effective_date_id] int NULL, 
	[budget_id] varchar(8000) NULL, 
	[exchange_rate] decimal(38,15) NULL, 
	[amount] decimal(18,2) NULL, 
	[reference] varchar(8000) NULL, 
	[description] varchar(8000) NULL, 
	[full_description] varchar(8000) NULL, 
	[material_id] varchar(8000) NULL, 
	[material_description] varchar(8000) NULL, 
	[quantity_loc] decimal(18,2) NULL, 
	[um] varchar(8000) NULL, 
	[comments] varchar(8000) NULL, 
	[user_id] varchar(8000) NULL, 
	[project_id] varchar(8000) NULL, 
	[batch_id] varchar(8000) NULL, 
	[currency_code] varchar(8000) NULL, 
	[segment_id] varchar(8000) NULL, 
	[line_number] int NULL, 
	[address_id] varchar(8000) NULL, 
	[document_id] varchar(8000) NULL, 
	[document_type] varchar(8000) NULL, 
	[company_code] varchar(8000) NULL, 
	[record_id] bigint NULL, 
	[last_updated_at] datetime2(6) NULL
);