CREATE TABLE [fi].[format_positions_for_report] (

	[format_position_id] int NULL, 
	[company_code] varchar(8000) NULL, 
	[description] varchar(8000) NULL, 
	[description_short] varchar(8000) NULL, 
	[english_description] varchar(8000) NULL, 
	[parent_position_id] int NULL, 
	[level] int NULL, 
	[sort_order] int NULL, 
	[path] varchar(8000) NULL, 
	[line_type] varchar(8000) NULL, 
	[calculation_formula] varchar(8000) NULL, 
	[is_summable] bit NULL, 
	[operator] varchar(8000) NULL, 
	[account_range_from] varchar(8000) NULL, 
	[account_range_to] varchar(8000) NULL, 
	[include_accounts] varchar(8000) NULL, 
	[exclude_accounts] varchar(8000) NULL, 
	[indent_level] int NULL, 
	[font_bold] bit NULL, 
	[font_italic] bit NULL, 
	[show_in_report] bit NULL, 
	[number_format] varchar(8000) NULL, 
	[decimal_places] int NULL, 
	[financial_category] varchar(8000) NULL, 
	[report_section] varchar(8000) NULL, 
	[is_active] bit NULL, 
	[created_date] datetime2(6) NULL, 
	[modified_date] datetime2(6) NULL, 
	[notes] varchar(8000) NULL, 
	[description_formatted] varchar(8000) NULL
);