CREATE TABLE [fi].[payment_terms] (

	[payment_code] varchar(8000) NULL, 
	[desc] varchar(8000) NULL, 
	[disc_pct] decimal(38,10) NULL, 
	[disc_days] int NULL, 
	[due_days] int NULL, 
	[due_date] datetime2(6) NULL, 
	[xfrom_inv] int NULL, 
	[disc_date] datetime2(6) NULL, 
	[xdue_inv] int NULL, 
	[dating] int NULL, 
	[user1] varchar(8000) NULL, 
	[user2] varchar(8000) NULL, 
	[user_id] varchar(8000) NULL, 
	[mod_date] datetime2(6) NULL, 
	[due_inv] int NULL, 
	[from_inv] int NULL, 
	[terms_int] int NULL, 
	[late_int] int NULL, 
	[base_date] datetime2(6) NULL, 
	[base_days] int NULL, 
	[min_days] int NULL, 
	[grace_days] int NULL, 
	[mtd_disc] int NULL, 
	[mtd_due] int NULL, 
	[company_code] varchar(8000) NULL, 
	[record_id] int NULL, 
	[last_updated_at] datetime2(6) NULL
);