CREATE TABLE [fi].[universal_journal_entries] (

	[account_id] varchar(8000) NULL, 
	[cost_center_id] varchar(8000) NULL, 
	[transaction_type] varchar(8000) NULL, 
	[entry_date] date NULL, 
	[effective_date] date NULL, 
	[amount] decimal(18,2) NULL, 
	[reference] varchar(8000) NULL, 
	[description] varchar(8000) NULL, 
	[unit_base] varchar(8000) NULL, 
	[user_id] varchar(8000) NULL, 
	[project_id] varchar(8000) NULL, 
	[error_flag] varchar(8000) NULL, 
	[batch_id] varchar(8000) NULL, 
	[currency_code] varchar(8000) NULL, 
	[currency_amount] decimal(18,2) NULL, 
	[segment_id] varchar(8000) NULL, 
	[line_number] int NULL, 
	[exchange_rate] decimal(18,6) NULL, 
	[address_id] varchar(8000) NULL, 
	[document_id] varchar(8000) NULL, 
	[document_type] varchar(8000) NULL, 
	[user_field_1] varchar(8000) NULL, 
	[user_field_2] varchar(8000) NULL, 
	[fx_indicator] varchar(8000) NULL, 
	[sub_account] varchar(8000) NULL, 
	[entered_currency_amount] decimal(18,2) NULL, 
	[entered_exchange_rate] decimal(18,6) NULL, 
	[exchange_rate_2] decimal(18,6) NULL, 
	[exchange_rate_type] varchar(8000) NULL, 
	[entered_exchange_rate_2] decimal(18,6) NULL, 
	[source_description] varchar(8000) NULL, 
	[company_code] varchar(8000) NULL, 
	[record_id] bigint NULL, 
	[last_updated_at] datetime2(6) NULL
);