CREATE TABLE [SAPHANADB].[IMATERIAL] (

	[MANDT] varchar(8000) NULL, 
	[MATERIAL] varchar(8000) NULL, 
	[MATERIALTYPE] varchar(8000) NULL, 
	[MATERIALGROUP] varchar(8000) NULL, 
	[MATERIALBASEUNIT] varchar(8000) NULL, 
	[MATERIALGROSSWEIGHT] decimal(38,18) NULL, 
	[MATERIALNETWEIGHT] decimal(38,18) NULL, 
	[MATERIALWEIGHTUNIT] varchar(8000) NULL, 
	[MATERIALMANUFACTURERNUMBER] varchar(8000) NULL, 
	[MATERIALMANUFACTURERPARTNUMBER] varchar(8000) NULL, 
	[AUTHORIZATIONGROUP] varchar(8000) NULL, 
	[ISBATCHMANAGEMENTREQUIRED] varchar(8000) NULL, 
	[CROSSPLANTCONFIGURABLEPRODUCT] varchar(8000) NULL, 
	[PRODUCTCATEGORY] varchar(8000) NULL, 
	[PRODUCTCHARACTERISTIC1] varchar(8000) NULL, 
	[PRODUCTCHARACTERISTIC2] varchar(8000) NULL, 
	[PRODUCTCHARACTERISTIC3] varchar(8000) NULL, 
	[PRODCHARC1INTERNALNUMBER] varchar(8000) NULL, 
	[PRODCHARC2INTERNALNUMBER] varchar(8000) NULL, 
	[PRODCHARC3INTERNALNUMBER] varchar(8000) NULL
);