CREATE TABLE [SAPHANADB].[IPLANT] (

	[MANDT] varchar(8000) NULL, 
	[PLANT] varchar(8000) NULL, 
	[PLANTNAME] varchar(8000) NULL, 
	[VALUATIONAREA] varchar(8000) NULL, 
	[PLANTCUSTOMER] varchar(8000) NULL, 
	[PLANTSUPPLIER] varchar(8000) NULL, 
	[FACTORYCALENDAR] varchar(8000) NULL, 
	[DEFAULTPURCHASINGORGANIZATION] varchar(8000) NULL, 
	[SALESORGANIZATION] varchar(8000) NULL, 
	[ADDRESSID] varchar(8000) NULL, 
	[PLANTCATEGORY] varchar(8000) NULL, 
	[DISTRIBUTIONCHANNEL] varchar(8000) NULL, 
	[DIVISION] varchar(8000) NULL, 
	[LANGUAGE] varchar(8000) NULL, 
	[ISMARKEDFORARCHIVING] varchar(8000) NULL
);