CREATE TABLE [dbo].[bronze_to_silver_control] (

	[task_id] int NULL, 
	[business_area] varchar(8000) NULL, 
	[load_type] varchar(8000) NULL, 
	[is_active] bit NULL, 
	[source_layer] varchar(8000) NULL, 
	[source_schema] varchar(8000) NULL, 
	[source_table] varchar(8000) NULL, 
	[target_layer] varchar(8000) NULL, 
	[target_schema] varchar(8000) NULL, 
	[target_table] varchar(8000) NULL, 
	[primary_keys] varchar(8000) NULL, 
	[watermark_column] varchar(8000) NULL, 
	[watermark_type] varchar(8000) NULL, 
	[last_watermark_value] varchar(8000) NULL, 
	[updated_at_column] varchar(8000) NULL, 
	[last_updated_at_value] varchar(8000) NULL, 
	[column_mapping_json] varchar(8000) NULL, 
	[last_run_status] varchar(8000) NULL, 
	[last_run_at] datetime2(6) NULL, 
	[last_message] varchar(8000) NULL, 
	[run_order] int NULL, 
	[comments] varchar(8000) NULL, 
	[created_at] datetime2(6) NULL, 
	[updated_at] datetime2(6) NULL, 
	[updated_by] varchar(8000) NULL, 
	[materialize_sql] varchar(8000) NULL, 
	[last_success_run_at] datetime2(6) NULL
);