CREATE TABLE [dbo].[bronze_to_silver_sql_control] (

	[task_id] int NULL, 
	[business_area] varchar(8000) NULL, 
	[is_active] int NULL, 
	[source_workspace] varchar(8000) NULL, 
	[source_lakehouse] varchar(8000) NULL, 
	[source_schema] varchar(8000) NULL, 
	[source_views] varchar(8000) NULL, 
	[target_views] varchar(8000) NULL, 
	[last_run_status] varchar(8000) NULL, 
	[last_run_at] datetime2(6) NULL, 
	[last_success_run_at] datetime2(6) NULL, 
	[last_message] varchar(8000) NULL, 
	[comments] varchar(8000) NULL, 
	[created_at] datetime2(6) NULL, 
	[updated_at] datetime2(6) NULL, 
	[updated_by] varchar(8000) NULL, 
	[frequency] varchar(8000) NULL, 
	[run_time] varchar(8000) NULL, 
	[snapshot_mode] varchar(8000) NULL, 
	[business_key_cols] varchar(8000) NULL, 
	[run_on_weekday] varchar(8000) NULL, 
	[run_on_day] varchar(8000) NULL, 
	[run_on_month_rule] varchar(8000) NULL, 
	[target_workspace] varchar(8000) NULL, 
	[target_lakehouse] varchar(8000) NULL, 
	[target_schema] varchar(8000) NULL, 
	[priority] int NULL, 
	[retry_count] int NULL, 
	[timeout_minutes] int NULL
);