CREATE TABLE [dbo].[silver_to_gold_control] (

	[task_id] int NULL, 
	[datamart_name] varchar(8000) NULL, 
	[business_area] varchar(8000) NULL, 
	[is_enabled] bit NULL, 
	[run_order] int NULL, 
	[table_type] varchar(8000) NULL, 
	[load_type] varchar(8000) NULL, 
	[source_lakehouse] varchar(8000) NULL, 
	[source_schema] varchar(8000) NULL, 
	[source_table] varchar(8000) NULL, 
	[source_filter] varchar(8000) NULL, 
	[target_lakehouse] varchar(8000) NULL, 
	[target_schema] varchar(8000) NULL, 
	[target_table] varchar(8000) NULL, 
	[surrogate_key] varchar(8000) NULL, 
	[business_keys] varchar(8000) NULL, 
	[watermark_column] varchar(8000) NULL, 
	[last_watermark_value] varchar(8000) NULL, 
	[column_mapping_json] varchar(8000) NULL, 
	[last_run_status] varchar(8000) NULL, 
	[last_run_at] datetime2(6) NULL, 
	[last_message] varchar(8000) NULL, 
	[created_at] datetime2(6) NULL, 
	[updated_at] datetime2(6) NULL, 
	[updated_by] varchar(8000) NULL
);