CREATE TABLE [dbo].[source_to_bronze_control_sap] (

	[task_id] int NULL, 
	[business_area] varchar(8000) NULL, 
	[load_type] varchar(8000) NULL, 
	[is_active] bit NULL, 
	[source_system] varchar(8000) NULL, 
	[dbms_type] varchar(8000) NULL, 
	[source_object] varchar(8000) NULL, 
	[object_type] varchar(8000) NULL, 
	[target_lakehouse] varchar(8000) NULL, 
	[target_schema] varchar(8000) NULL, 
	[target_table] varchar(8000) NULL, 
	[primary_keys] varchar(8000) NULL, 
	[watermark_column] varchar(8000) NULL, 
	[watermark_type] varchar(8000) NULL, 
	[last_watermark_value] varchar(8000) NULL, 
	[updated_at_column] varchar(8000) NULL, 
	[last_updated_at_value] varchar(8000) NULL, 
	[column_mapping_json] varchar(8000) NULL, 
	[last_run_status] varchar(8000) NULL, 
	[last_run_at] datetime2(6) NULL, 
	[last_message] varchar(8000) NULL, 
	[run_order] int NULL, 
	[comments] varchar(8000) NULL, 
	[created_at] datetime2(6) NULL, 
	[updated_at] datetime2(6) NULL, 
	[updated_by] varchar(8000) NULL, 
	[last_success_run_at] datetime2(6) NULL, 
	[object_description] varchar(8000) NULL
);